sepluginloader/PluginHub

Plugins/SEWorldGenPlugin_v2/github.xml, Plugins/SEWorldGenPlugin_v2/steam.xml
Added the latest SEWorldGenPlugin version finally as a GitHub plugin and grouped the steam and github verson together.
=> Added SEWorldGenPlugin as a github plugin 

Plugins/NoNewsPlugin.xml
Hope this finally fixes the problem once and for all!
=> No News Plugin Fix

Plugins/SEWorldGenPlugin_v2/github.xml
This version puts GPS generation on an extra Thread to improve performance and fixes a GUI bug
=> Updated SEWG to newest version.

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the commit to the lastest SEWG version that introduces a new World Generator option
=> Updated commit to fit new SEWG version

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the github version commit id to the latest hotfix version
=> Updated github version of SEWG to latest hotfix

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the commit id for the GitHub version of SEWG to the lastest version v2.0.6.6
=> Updated SEWG to latest version v2.0.6.6

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the SEWorldGenPlugin v2 commit id to the latest version 2.0.6.7
=> Updated SEWorldGenPlugin commit id to latest version

Plugins/SeamlessClientPlugin.xml
- Patched for Heavy-Industry Update
=> Seamless Client Plugin Update

Plugins/SEWorldGenPlugin_v2/github.xml
Updated SEWG commit id for version 2.0.6.8, hotfix for save file location.
=> Updated SEWG to commit for version 2.0.6.8, hotfix for save file location

Plugins/DiscordRichPresence.xml
=> Added Discord Rich Presence

Plugins/DiscordRichPresence.xml
Removed un-used read thread
Fixed crash if discord closes unexpectedly
=> Rich Presence fixes

Plugins/DiscordRichPresence.xml
Updated rich presence server list
=> Updated Rich Presence

Plugins/ScrollableFOV/github.xml
=> Scrollable FOV crash

Plugins/ScrollableFOV/github.xml
Fixed ScrollableFOV causing soft crash on world reload
=> Fixed for world loading

Plugins/SEWorldGenPlugin_v2/github.xml
The commit id was updated to version 2.1 of the plugin, which reworked Networking of the plugin, added the Star system designer and some smaller changes.
=> Updated commit to version 2.1 of the plugin.

Plugins/SEWorldGenPlugin_v2/github.xml
Updated SEWG commit version to plugin version 2.1.0.1
=> Updated SEWG commit version to 2.1.0.1

Plugins/SEWorldGenPlugin_v2/github.xml
Updated commit to version 2.1.1 of SEWG that added planet removal from the plugins system
=> Updated commit to version 2.1.1 of SEWG

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the commit id of SEWG to version 2.1.1.1 of the plugin
=> Updated SEWG commit id to version 2.1.1.1 commit

Plugins/ScrollableFOV/github.xml
Fixed ModAPI for scrollable FOV
=> ScrollableFOV update

Plugins/HeadTracking.xml
A head tracking plugin for SE.
=> HeadTrackingPlugin

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the commit id to SEWG version 2.1.1.2, which only fixes some bugs
=> Updated SEWG version to 2.1.1.2

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the commit id of github SEWG to version 2.1.1.3, small memory leak hotfix
=> Updated SEWG commit id to SEWG v2.1.1.3

Plugins/CustomLoadingBackgrounds.xml
Fixed issue where video would play ingame after loading into game if you did not add custom videos or images to the  main menu.
=> Fixed video bug.

Plugins/NoLogging.xml
Updated commit id to fix plugin not downloading.
=> NoLogging FIx

Plugins/ToolbarManager.xml
New client plugin: Toolbar Manager
=> New client plugin: Toolbar Manager

Plugins/InGameExit.xml
Changed assembly info so that a future plugin can detect if the plugin is loaded.
=> InGameExit Minor Patch.

Plugins/SEWorldGenPlugin_v2/github.xml
Optimization of the plugin and bug fixes
=> Updated SEWG to version 2.1.2.0

Plugins/ScrollableFOV/github.xml
Plugin now supports better smoothing of camera motion
=> Better smoothing

Plugins/FPSCounter.xml
Plugin Name: FPS Counter 
Description: FPS Counter for Space Engineers.
Link: https://github.com/WesternGamer/FPSCounter/tree/master
=> FPSCounter Plugin

Plugins/ScrollableFOV/github.xml
The view will now smooth scroll in and out, not just in.
=> Minor update to scrolling

Plugins/FPSCounter.xml
Fixed FpsCounter overlay closing sometimes.
=> FPSCounter Update 

Plugins/SEWorldGenPlugin_v2/github.xml
Updated SEWG commit to version 2.1.3.0. This adds a new harmony patch to fix encounters not spawning
=> Updated SEWG commit to version 2.1.3.0

Plugins/SEWorldGenPlugin_v2/github.xml
Updated SEWG version to 2.1.4.0. This adds a setting for planet gravity falloff.
=> Updated SEWG version to 2.1.4.0.

Plugins/CustomLoadingBackgrounds.xml
-Added option for a cleaner loading menu.
-Background image on main menu is now its separate screen.
-XML Reader system upgraded for future updates.
=> CustomLoadingBackgrounds v1.3.0

Plugins/CustomLoadingBackgrounds.xml
=> Custom Menu Backgrounds bug fix

Plugins/RDR2DeathScreen.xml
Fixed bugs and plugin is ready for release.
Repo: https://github.com/WesternGamer/RDR2DeathScreen
=> RDR2DeathScreen Release

Plugins/SeamlessClientPlugin.xml
Temp remove seamless plugin for update
=> Temp Remove seamless client plugin

Plugins/SEWorldGenPlugin_v2/github.xml
Updated SEWG for Warfare II update and added new global setting for fixed planet sizes
=> Updated SEWG for Warfare II update

Plugins/MorePPSettings/github.xml
Added desc and updated more PP settigns plugin
=> Added desc and updated plugin

Plugins/SEWorldGenPlugin_v2/github.xml
Added support for plugin config button of PluginLoader
Added variable gps discovery setting
=> Update SEWG version to 2.1.6.0

Plugins/SEWorldGenPlugin_v2/github.xml
Hotfix for SE crash due to faulty world config introduced in last update
=> Updated SEWG to version 2.1.6.1

Plugins/Mods/Accelerometer.xml
Adds my [accelerometer](https://steamcommunity.com/sharedfiles/filedetails/?id=2426611028) (steam page) mod. I'm hoping it will just work:tm:, please let me know if theres some stuff I've overlooked in the specification
=> feat: add Accelerometer mod

Plugins/CustomLoadingBackgrounds.xml
Added ingame config system.
Repo: https://github.com/WesternGamer/CustomLoadingBackgrounds
=> CustomLoadingBackgrounds Update 

Plugins/RDR2DeathScreen.xml
Repo: https://github.com/WesternGamer/RDR2DeathScreen
=> RDR2DeathScreen Bloom Fix

Plugins/FPSCounter.xml
Fixed issue where plugin would not work due to files for ME version being used in compiling the SE version.
=> FPSCounter Bug Fix

Plugins/FPSCounter.xml
Fixed config file not being created.
=> FPSCounter Bugfix

Plugins/FPSCounter.xml
Changed one line of code to fix plugin not working at last.
=> FPSCounter Actual Fix 

Plugins/CustomLoadingBackgrounds.xml
Fixed issue where main menu images would be selected from the wrong folder.
=> CustomLoadingBackgrounds Minor bug fix

Plugins/CustomLoadingBackgrounds.xml, Plugins/FPSCounter.xml
Added feature to show custom overlays in main menu and loading menu.
Commit: https://github.com/WesternGamer/CustomLoadingBackgrounds/commit/ad730512f6befe410ff261084f09c7d610137226
FPS Counter:
Added stats to title bar.
Commit: https://github.com/WesternGamer/FPSCounter/commit/ed7afd059a15c977263e7c45261fdffaa1b0044e
=> Custom Menu Backgrounds 1.5 Update & FPS Counter Update

Plugins/NoForcedCameraZoom.xml
not as extreme as it was previously, but its a start.
=> New implementation for increased zoom-in

Plugins/SEWorldGenPlugin_v2/github.xml
Updated SEWG for new SE version
=> Updated plugin for new SE version

Plugins/SeamlessClient.xml
- Fixed possible issues with client-side crashes
- Added F3 menu Nexus wide playerlist
=> Updated Seamless

Plugins/SeamlessClient.xml
- Fixed GPS points not saving/updating when switching servers. Will required a server plugin update.
=> Seamless HotFix

Plugins/SEWorldGenPlugin_v2/github.xml
Updated commit version of SEWG to latest version 2.1.6.3
=> Updated SEWG commit to latest version

Plugins/SeamlessClient.xml
=> Updated to fix possible GPS issues

Plugins/ReflectiveWater.xml
=> Reflective Billboards/Water Plugin

Plugins/FPSCounter.xml
[Added option to hide stats when hud is hidden.](https://github.com/WesternGamer/FPSCounter/commit/0dfa77f9ee242ba9a4f3b2effb2d8cf8b85f67e0)
=> FPSCounter Update 1.1.3

Plugins/Mods/EasyProgrammableBlockButtons.xml
Based on: https://steamcommunity.com/workshop/filedetails/?id=1805199276
Moves the Edit and Recompile Buttons of the Programmable Block to the top of the terminal.
=> Create Easy Programable Block Buttons

Plugins/AdminAbilitiesTracker.xml
=> AdminAbilitiesTracker

Plugins/RespawnMenuImprovements, Plugins/RespawnMenuImprovements.xml
new plugin. reopened pull request to fix a plugin naming error.
=> Respawn Menu Improvements

Plugins/Mods/GPSHelper.xml
Adding GPS Helper Mod with author permission 
Kaito  [author] Jul 1 @ 1:20pm 
No, I had not considered it yet. Feel free to have a look. I'm kinda busy irl right now, so it would be a while before I could look.
In theory it all runs on the client, but you'll have to check the API.
Doc1979 Jun 28 @ 4:37pm 
Does this use server only commands? If not, have you thought of making it into a PluginLoader plugin? I was thinking of looking at your github to see if I could convert it myself, but if its already on your todo list, I'll wait
=> Adding GPS Helper Mod with author permission

Plugins/SEWorldGenPlugin_v2/github.xml
Updated SEWG commit id to newest version fixing bugs with its gps
generation.
=> Updated SEWG commit id

Plugins/DisableExportModel.xml
disables the dumb export model thing that more often than not crashes the game
=> new plugin

Plugins/ParticleEditor.xml
=> Particle Editor v1.01

Plugins/ScrollableFOV/github.xml
=> Updated ScrollableFOV

Plugins/BuildFreedom.xml
Tools for builders. Currently has paste freedom (removes collision check for pasting)
=> Build Freedom

Plugins/SlowMo.xml
Cinematic tool that slows sim speed + modifies particles when activate. Offline use only
=> SlowMo Plugin

Plugins/SEWorldGenPlugin_v2/github.xml
This version adds a patch to fix Keens directory copy function to also
copy sub directories and also fixes some visual stuff in the Star system
designer of the plugin.
=> Updated SEWG commit id to latest version.

Plugins/RemoveIntroVideoPlugin.xml
Fixed certain main menu modifications from other plugins not working.
- [00e537de2917e21c4278f870b910e55720922e4a](https://github.com/WesternGamer/RemoveIntroVideoPlugin/commit/00e537de2917e21c4278f870b910e55720922e4a)
- [554d6f01b8861f5d9bf79a824aef3c0d2d9a48bb](https://github.com/WesternGamer/RemoveIntroVideoPlugin/commit/554d6f01b8861f5d9bf79a824aef3c0d2d9a48bb)
- [edcda944e861aa4bfadba66fee6e3ee880406789](https://github.com/WesternGamer/RemoveIntroVideoPlugin/commit/edcda944e861aa4bfadba66fee6e3ee880406789)
- [f22bcfff47ed1fb7c8d9a8958e8a87b4e9b5f9ee](https://github.com/WesternGamer/RemoveIntroVideoPlugin/commit/f22bcfff47ed1fb7c8d9a8958e8a87b4e9b5f9ee)
=> Remove Intro Video Plugin 1.1.0 Update

Plugins/RemoveIntroVideoPlugin.xml
Redone code to force the main menu to close.
=> RemoveIntroVideoPlugin Fix

Plugins/ParticleEditor.xml
=> Particle Editor v1.02

Plugins/FPSCounter.xml
Game name in title bar can now be changed by other plugins.
=> FPSCounter Update

Plugins/ParticleEditor.xml
Small changes for a fix :} details in the repo of course.
=> Particle Editor v1.03

Plugins/Mods/SilentSuit.xml
Request to add my mod to sepluginloader
description:
```
Removes all suit voice warning
This mod keeps the suit voice silent.
You can find my source code here : https://github.com/WalTho/SilentSuit/tree/main/SilentSuit
```
=> Silent Suit

Plugins/FPSCounter.xml
Update to FPS counter to add dispose code.
=> FPS Counter Update

Plugins/SEWorldGenPlugin_v2/github.xml
Updated commit id of SEWG v2 to latest version of the plugin. [Patch notes](https://github.com/thorwin99/SEWorldGenPlugin/releases/latest)
=> Updated commit id of SEWGv2

Plugins/SEWorldGenPlugin_v2/github.xml, plugins.sha1
Updated commit id of SEWG v2 to latest version of the plugin. Just smaller bug fixes and optimizations. [Patch notes](https://github.com/thorwin99/SEWorldGenPlugin/releases/tag/v2.1.6.8)
=> Updated SEWG commit id to latest plugin version v2.1.6.8

Plugins/Mods/ButtonPad.xml, Plugins/Mods/CameraOverTheShoulder.xml, Plugins/Mods/ElectricNetworkInfo.xml, Plugins/Mods/TouchScreenAPI.xml
Added TouchScreenAPI, Touch Apps and Camera Over the shoulder to mods list
=> Adriano's Mods

Plugins/SEWorldGenPlugin_v2/github.xml, plugins.sha1
A critical fix for game freezing when using the economy system that generates contracts.
=> Updated SEWG to latest commit

Plugins/Mods/Flight Vector.xml
Request to add a mod that is clientside-only, and locally draws the directional vectors of the currently occupied grid.
=> Create Flight Vector.xml

Plugins/Mods/GPSExtended.xml
The mod can be found here: https://steamcommunity.com/sharedfiles/filedetails/?id=2958267813
It's a really simple mod that allows placing of a GPS point at a distance from the player. The entire thing exists in the event handler for MyAPIGateway.Utilities.MessageEntered. It simply parses the <distance> and <name> arguments and then places a GPS at an offset from the current players position, in the direction the camera is looking.
There is error checking for arguments, and the whole thing is wrapped in a try/catch which dumps the exception to the SE log.
=> Create mod link file for mod 'GPS Extended'

Plugins/DiscordRichPresence.xml
Fixed plugin crashes and added more servers
=> Discord RP plugin

Plugins/Mods/BuildColors.xml
At the request of some users, I would like to add my BuildColor mod to this hub. However, I'm uncertain whether the Rich Hud Master dependency needs to be included here too.
=> Adding BuildColors

Plugins/DisableSpectatorMouseSensitivity.xml
'Disables' the ctrl+scrollwheel keybind in spectator mode
=> Add DisableSpectatorMouseSensitivity

Plugins/CreativeWorldSave.xml
Tool for creating a mod-accurate local world for ship building in creative. Constructs a new save using the mod list and settings of the current session, purging everything else.
=> Creative World Save

Plugins/AddMissingSearchBoxes.xml
https://github.com/WesternGamer/AddMissingSearchBoxes/commit/b9ca20f07f205619f2029075c35eb99f680b3403
=> Add Missing Search Boxes 1.1.0

Plugins/SEWorldGenPlugin_v2/github.xml
Updated the SEWG commit id to latest version to make it compatible with the newest game version. Changelog can be found [here](https://github.com/thorwin99/SEWorldGenPlugin/releases/tag/v2.1.6.13)
=> Update SEWG commit id

Plugins/AddMissingSearchBoxes.xml
https://github.com/WesternGamer/AddMissingSearchBoxes/commit/38ed7357c516c5b084d3e77f574111c649d64b99
=> Add Missing Search Boxes Bug Fix

Plugins/PaintJob.xml
Removed the previous PR due to plugin using dryioc. It's been removed in this version.
=> Add paint job plugin

Plugins/GpsFolders.xml
bugfixes and new minor features
=> GpsFolders v1.0.1

Plugins/GpsFolders.xml, Plugins/RespawnMenuImprovements.xml
update gps folders and rename respawn menu improvements
=> update 2 plugins

Plugins/GPSMarkerScaling.xml
This plugin allows you to change the scale of GPS icons.
https://github.com/WesternGamer/ProperGPSMarkerScaling
=> GPS Marker Scaling

Plugins/CreativeModeEnhancements.xml
Tools and changes that make building in creative mode easier.
https://github.com/WesternGamer/CreativeModeEnhancements
=> Creative Mode Enhancements

Plugins/ResizableChat.xml
ResizableChat hotfix due to keen removing MyGuiManager.LanguageTextScale
=> ResizableChat hotfix

Plugins/CustomMenuBackgrounds.xml
Added support for jpg image files.
Added option to disable/enable loading screen load progress indicator.
=> Custom Menu Backgrounds 1.6.0 Update

Plugins/Mods/ProjectorCrossSection.xml
https://steamcommunity.com/sharedfiles/filedetails/?id=3023809354
=> Add Projector Cross Section (Mod)

Plugins/Mods/MultiplayerPredictionSwitcher.xml
https://steamcommunity.com/sharedfiles/filedetails/?id=3032417765
=> MultiplayerPredictionSwitcher (Mod)

Plugins/BallTurretHelper.xml
Fixed some bugs and made changes to Ball Turret Helper
=> Fixed some bugs

Plugins/Mods/SgmHud.xml
Please add SgmHud as mod-plugin. For now it is only a personal test project to learn about HUD modifications that can run as a plugin.
=> Add SgmHud as a mod-plugin.

Plugins/SeamlessClient.xml
=> Updated Seamless Client to V2

Plugins/SeamlessClient.xml
=> Seamless update v2.0.0.3

Plugins/Mods/InvalidsAlternateUISound.xml
https://steamcommunity.com/sharedfiles/filedetails/?id=3125206981
=> InvalidsAlternateUISound (mod)

Plugins/AddMissingSearchBoxes.xml
Code cleanup.
Fixed GridInfoControllerPatch being broken due to game update.
=> Add Missing Search Boxes Update

Plugins/Mods/ConveyorDiagram.xml
CD shows xray views of ships and draws conveyor lines/junction/nodes for troubleshooting or damage assessment.  Has provisions to prevent peeking inside enemy grids.
=> Add Conveyor Diagram mod to PL

Plugins/Mods/LeakFinder.xml
Mod that can be used entirely from clientside of course, same stuff from my BuildInfo mod.
=> LeakFinder.xml

Plugins/Mods/Flight Vector.xml
Added dependency prior to rewrite using Text Hud API for screenspace symbol draw and F2 menu options.
=> Update Flight Vector.xml - add Text Hud API Dependency

Plugins/ProjectedLights.xml
=> Update ProjectedLights to v1.0.3.0

Plugins/FasterLoadGameScreen.xml
This is a plugin that makes the loading time of the Load Game menu faster, especially when you have many worlds.
=> Faster Load Game Screen

Plugins/StoreGUIFix.xml
Fix grayed out buy/sell buttons
=> Store GUI Fix - Bugfix

Plugins/FPSCounter.xml
Fixed an issue where sim speed was lower than normal when using the plugin. 
https://github.com/WesternGamer/FPSCounter/commits/master/
=> FPS Counter 1.6.0

Plugins/HideQuickStartButton.xml, Plugins/InGameWorldLoading.xml, Plugins/RevertNewGameScreen.xml
Fix for update 1.204 signals update.
https://github.com/WesternGamer/InGameWorldLoading/commit/148d52d2d9b43a7f800c97328d9fcbd8927dc1df
=> In Game World Loading Update 1.0.1

Plugins/GpsFolders.xml
update is unrelated to the recent game update
=> Update GPS Folders and More

Plugins/FasterLoadGameScreen.xml
Fixed issue where not all worlds would be shown in the new game screen.
https://github.com/WesternGamer/FasterLoadGameScreen/commit/206c3193571b70edf650eda8b007da15103a560f
https://github.com/WesternGamer/FasterLoadGameScreen/commit/11c760e10f66a0ddc914eafd42283ab8b29b21d1
https://github.com/WesternGamer/FasterLoadGameScreen/commit/9aca35b902d70aa298d7f1c9c1a30a2f20ba7042
=> Faster Load Game Screen 1.0.1

Plugins/Mods/GVInventorySorter.xml
https://steamcommunity.com/sharedfiles/filedetails/?id=3082595868
Adding with permission from Steam author Merii @highlyunavailable
=> Add GV Inventory mod

Plugins/Mods/HudLCDv2.xml
Add HudLCD v2 with multi screen support
https://steamcommunity.com/sharedfiles/filedetails/?id=2005632342
=> Add HudLCDv2

Plugins/JetpackGravityAlignment.xml
=> added jetpack gravity alignment plugin

Plugins/SEWorldGen.xml
Fixed incompatibilities with SE 2.105
=> Update SEWorldGen.xml to the new SEWorldGen commit id

Plugins/Mods/Vans Toolbar Tweaks, Plugins/Mods/VansToolbarTweaks.xml
I would like [Vans Toolbar Tweaks](https://steamcommunity.com/sharedfiles/filedetails/?id=3357036851) to be added to the plugin loader.
=> Create Vans Toolbar Tweaks

Plugins/Mods/L.U.C.1.A.N. Suit A.I. - Ghost Industries Ltd.
The XML File entry for inclusion in the client side mod list for the S.E. Plugin Loader.
=> Create L.U.C.1.A.N. Suit A.I. - Ghost Industries Ltd.

Plugins/ModNetworkProfiler.xml
This will require https://github.com/sepluginloader/PluginLoader/pull/73 in order to compile.
=> Add ModNetworkProfiler Plugin

Plugins/Zoom.xml
Updates to Config GUI and ScrollableFOV, tackling an undocumented 'Zoom Lock' bug
'Zoom Lock' now added as a configurable feature, no longer a bug
=> Zoom Update

Plugins/Mods/GFA - Jump to Lightspeed.xml
This is a mod that changes the jump drive sound and visual effects to the star wars hyperdrive effect, mod was made by enenra.
This mod works on client side only.
=> Added GFA - Jump to Lightspeed

Plugins/AutoRemoveStone.xml, Plugins/JumpSelector.xml
Since Dude is pretty inactive and I use his plugins I decided to update them and have changed his repos in the xml to mine until he accepts my pull requests or updates them himself.
=> Updated Dudes Plugins

Plugins/SeamlessClient.xml
Still getting a bug where sometimes your character is stuck when switching with only a character
=> Slight more fixed

Plugins/TargetCamera.xml
=> Target camera plugin request
