- Plugins/SEWorldGenPlugin_v2/github.xml
It should fix the issues it had with the plugin loader github plugins by hardcoding the storage folder and removing a duplicate file that should not have been on the github thanks to @austinvaness.
> Updated SEWorldGenPlugin to latest version

- Plugins/NoNewsPlugin.xml
This plugin removes the DLC and News Elements from the main menu and the pause menu. This was requested by someone in the Plugin Loader Discord under plugin-requests. Here is the link to the repository of the plugin: https://github.com/WesternGamer/No-News-Plugin
Also here is an image of what the plugin modifies:
> Add No News Plugin

- Plugins/RemoveIntroVideoPlugin.xml
The plugin disables the intro video that is played when you open Space Engineers. The purpose of this plugin is to make disabling the intro video more streamlined for users of PluginLoader.
> Add RemoveIntroVideoPlugin

- Plugins/SEWorldGenPlugin_v2/github.xml
The previously merged commit id was wrong and doesn't exist in the SEWG repository anymore
> Fixed wrong commit id

- Plugins/SeamlessClientPlugin.xml
Where does it read versions from in Github? I thought it was in the XML file... but I was wrong.
> Update SeamlessClientPlugin to new version

- Plugins/InstantExit.xml
This plugin is a plugin to help you debug/develop Space Engineers plugins without the hassle of terminating the Space Engineers process every time you build the plugin.
> InstantExit Plugin

- Plugins/HideVersionString.xml
-Fixed issue where options button was missing on main menu. This should also prevent future issues with other plugins.
-Moved version string to bottom right in option selection menu.
> HideVersionString 1.0.1 Update

- Plugins/FileCleaner.xml
- Plugins/NoLogging.xml
The NoLogging plugin disables logging to improve performance. It does not disable logging entirely like errors/exceptions and certain urgent warnings. The FileCleaner plugin deletes temporary files and log files when you launch the game.
> NoLogging Plugin & FileCleaner Plugin

- Plugins/FileCleaner.xml
Fixed issue where exception would be thrown when a folder(s) that the plugin is searching for does not exist.
> FileCleaner bug fix

- Plugins/InGameWorldLoading.xml
Plugin: InGameWorldLoading
Description: Adds the ability to load, join, or start a new world from ingame.
Link: https://github.com/WesternGamer/InGameWorldLoading
> New Plugin

- Plugins/RDR2DeathScreen.xml
I made the plugin download the required files once only when the plugin is ran for the first time. I also redid the repo to show the correct project as it was showing the old project instead.
Source: https://github.com/WesternGamer/RDR2DeathScreen
> RDR2 Death Screen With Changes

- Plugins/RDR2DeathScreen.xml
-Hopefully fixed null reference issue when switching between nexus servers.
> RDR2DeathScreen Nexus Server Fix.

- Plugins/EasyBlockRenaming.xml
Adds controls to nearly all block types that allows you to easily rename multiple blocks at once.
- Multiple Block Renaming: Simply select all the blocks you want to rename, enter the new name they should receive in the "New Naming" field, and then press the "Replace Name" button.
- Prefix and Suffix Names: The prefix and suffix options allow you to add the text in the "New Naming" field to the existing block names. "Prefix Name" will add the text to the beginning of the block name, while "Suffix Name" will add the text to the end of the block name.
- Reset Name: The "Reset Name" button will reset the name of selected blocks back to their default names (the name they receive when you initially build the block). Please note it does not suffix the block with numbers. This can be useful if …
> Add new plugin

- Plugins/AdminAbilitiesTracker.xml
- Plugins/AutoFactionChat.xml
AutoFactionChat is a QoL plugin that will make the default channel the faction channel instead of the global channel.
I accidentally left some weird spaces in the description for my other plugin, so I removed those.
> Add AutoFactionChat Plugin and update description for AdminAbilitiesTracker

- Plugins/UnlimitedDepositAndWithdrawalAmount.xml
capped withdrawal amount to int.maxvalue, otherwise it can overflow and create negative credits in users inventory.
> Update UnlimitedWithdrawalAmount plugin

- Plugins/SeamlessClient.xml
This updates the seamless client to reference the new maintainers (can verify via going to https://github.com/Casimir255/SeamlessClientPlugin) and home and releases the 1.5.0 update.
Changes in 1.5.0 mostly code clean-up as well as some performance improvements to the client.
> Update Seamless maintainer and release 1.5.0

- Plugins/FpsUnlocker.xml
Hi! :) I created a new plugin that lets players change the framerate cap on Space Engineers. The default framerate cap is 120 fps. This plugin lets one adjust the framerate cap to any value they desire in the config with a slider from 60fps to 500 fps. A player could set it to match their monitor rate  such as 144 fps, 165fps, 240fps, etc. My plugin sets the cap to 500 by default. 
I also notice my plugin helps greatly with performance for the Camera LCD Mod when it's set to such a high framerate like 500 fps. I hope everyone finds the plugin useful! 
https://github.com/ritaelyn/FPSUnlocker
> Add FpsUnlocker Plugin to Plugin Loader (add FpsUnlocker.xml)

- Plugins/AddMissingSearchBoxes.xml
This plugin currently adds a search box to the factions menu and comms menu in the terminal.
> Add Missing Search Boxes Plugin

- Plugins/Mods/Flight Vector.xml
- Plugins/Mods/Status Report.xml
-Minor fixes to description of Flight Vector, including link to Steam Workshop
-Add Status Report, client-side only mod that gathers information about the current grid/inventory/systems
> Revise Flight Vector and add Status Report

- Plugins/OpenLinksInDefaultBrowser.xml
Forces the game to open links in the default browser instead of the Steam overlay.
https://github.com/WesternGamer/OpenLinksInDefaultBrowser
> New plugin: Open Links In Default Browser

- Plugins/Mods/BuildInfo_BleedingEdge.xml
I've also made these mods to self-kill if a "higher priority version" exists so that players can bring this version into servers that have regular version and not have duplicated behavior.
> BuildInfo bleeding edge version

- Plugins/GPSMarkerScaling.xml
Fixed an issue where the plugin would not load if the folder that normally contains the config does not exist.
https://github.com/WesternGamer/ProperGPSMarkerScaling/commit/aa4d67d56f2427728475d6e8cc82ca724c128aff
> GPS Marker Scaling Bug Fix

- Plugins/Mods/BuildVision.xml
- Plugins/Mods/RichHudMaster.xml
I've updated Build Vision to disable features depending on server-side code if PLUGIN_LOADER is defined. The RHM dependency was already purely client-side and will work as-is.
> Add Build Vision and Rich HUD master as mod plugins

- Plugins/TimeoutFix.xml
The TimeoutFix plugin was written originally in 2020 by Space Engineers community member _rexxar_, now retired.
Until now, the TimeoutFix plugin was distributed among the Space Engineers community in binary form (dll).
Instead, now that we have PluginLoader, I propose to distribute it via the plugin hub, with reviewable source taken from the decompilation of the original dll. No other modifications were made.
I'm hoping this will put an end to the practice of sharing the dll and associated risks, in favor of the more trustworthy PluginLoader.
For more information about what the plugin does, see the [readme](https://github.com/StalkR/Space-Engineers-Timeout-Fix), in particular the [reddit post](https://www.reddit.com/r/spaceengineers/comments/f7ul3s/fix_for_server_is_not_responding_error/) …
> plugins: add TimeoutFix

- Plugins/ProjectedLights.xml
This is a plugin that gives (almost) every interior type block spotlight qualities, just without shadows (by default). (Also known as light masks.) The idea came after comparing 2014's Alien: Isolation with Space Engineers. The survival horror game used light masks extensively to give light sources a more interesting appearance and I wanted to replicate that look in SE.
> Added the Projected Lights plugin.

- Plugins/ProjectedLights.xml
This one has a couple of changes, and doesn't crash when placing a search light in survival.
For example there is now less of a grayish light showing when using colored lights.
> Update to v1.0.1.0 of Projected Lights

- Plugins/GrabSingleItem.xml
Allows people to alt + click in the inventory terminal to transfer single items.
Similar to ctrl + click, except only transfers 1 instead of 10.
> Add GrabSingleItem Plugin

- Plugins/FasterLoadGameScreen.xml
Fixed issue where you could not use worlds on the Original Content tab in the New Game Screen. Fixed crash caused by the same issue if you tried customizing worlds on the Original Content tab.
https://github.com/WesternGamer/FasterLoadGameScreen/commit/f6912e5a535273dfc2d26a27f0cccc6f8ee75528
https://github.com/WesternGamer/FasterLoadGameScreen/commit/d5be514dd923d421db280a2c90ae0a49a4e8d17e
> Update Faster Load Game Screen to 1.0.2

- Plugins/RDR2DeathScreen.xml
https://github.com/WesternGamer/RDR2DeathScreen/commit/45c2ed3ce0b0bbdbf188390ac500ae56cd7fa67a
https://github.com/WesternGamer/RDR2DeathScreen/commit/eaa917a023f5cb89a7161ac5a63db9ce861600a1
- Project refactored.
- MyGuiScreenGamePlay.DisableInput will behave normally if the death screen is not present. This is to support other plugins looking to use MyGuiScreenGamePlay.DisableInput, but without disabling unhandled inputs.
> RDR2 Death Screen 1.0.1

- Plugins/GPSMarkerScaling.xml
Added support for 1.205 Contact update.
https://github.com/WesternGamer/ProperGPSMarkerScaling/commit/ca888baaae769a469ed6298e15667e7c7a215391
https://github.com/WesternGamer/ProperGPSMarkerScaling/commit/1e593b32908a21fd0fcdd7926ca8a35ef6b315d3
https://github.com/WesternGamer/ProperGPSMarkerScaling/commit/c2e2e6041e52e18b637563175bb571df0f6c4523
> Update GPS Marker Scaling

- Plugins/AddMissingSearchBoxes.xml
Fixed GridInfoControllerPatch code.
https://github.com/WesternGamer/AddMissingSearchBoxes/commit/69d01260643fcd7901bf41a52917c1f119cf6de8
> Update AddMissingSearchBoxes - Support for 1.205

- Plugins/AssemblerSorting.xml
Sorts assemblers by selected block first, then completed blocks, then by display name.
> Add Assembler Sorting Plugin

- Plugins/Mods/RationalisedBuildMenu.xml
The only thing this mod does is adding `BlockVariantGroups_Rationalised.sbc` to set up better block groups than Keen did in the Contact update. This mod has no code at all and affects only the blocks groups in the G menu and the player's character toolbar.
> Mod: Rationalised Build Menu

- Plugins/FixMissingTreesPlugin.xml
Plugin implementing potential fix for https://support.keenswh.com/spaceengineers/pc/topic/44535-client-side-environment-item-e-g-tree-lod-issue
This was caused by the function populating environment items incorrectly removing the number of items that had already been spawned from the number of items considered for the target LOD.
i.e. if there were 39 items spawned and the target LOD should consider 107 items, it was only considering 68 items
The patch in this plugin will be inert if the fix therein is picked up by Keen.
> Add plugin to fix invisible trees

- Plugins/Mods/SEENG_APEX.xml
> Add SEENG-APEX (mod)

- Plugins/Mods/BlockIndexer
I wrote a simple mod to automatically add index suffixes to selected block names. It works almost exactly like EasyBlockRenaming.
I would like it to be availiable to launch from client side.
> Add BlockIndexer mod entry to client mods list

- Plugins/ToolHelper.xml
The ToolHelper plugin adds terminal controls to show the radius of ship tools.
[Example video](https://streamable.com/tc8ze0)
> Add ToolHelper plugin

- Plugins/Mods/CastSpectatorSC.xml
https://steamcommunity.com/sharedfiles/filedetails/?id=3299682578&searchtext=cast+spectator
enhancements to the F8 spectator camera like a smoothing mode, state saving/loading, auto switching between presets, and more tracking options
https://github.com/user-attachments/assets/12e7e148-7cf1-44fc-beb4-ad4c390d8cc9
> Create CastSpectatorSC.xml (mod)

- Plugins/Mods/Flight HUD.xml
This should add the [Flight HUD mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3445281509) to the pluginloader, if I have goofed up the XML please lmk its my first time doing stuff like this lol.
This mod displays your current azimuth (heading), elevation and your roll (via an artificial horizon). This was crafted for use on the sigma draconis expanse server, but I can see it having use on other servers.
This is also the first mod I have published to the workshop so again I may have goofed things up on that side as well lol.
> Adding the Flight HUD mod

- Plugins/AddMissingSearchBoxes.xml
Updated Add Missing Search Boxes to remove the patched in search box in the spawn menu, as it has been added as a vanilla feature in 1.206.
https://github.com/WesternGamer/AddMissingSearchBoxes/commit/b920d59d308abd5f55f7d25a4071c585f1a8d8e8
https://github.com/WesternGamer/AddMissingSearchBoxes/commit/d1b19a04f4649e308e553196bd64758f2e431638
https://github.com/WesternGamer/AddMissingSearchBoxes/commit/61b858a68f5ed31df13ce40b950047e9c3f5d57d
> Update Add Missing Search Boxes

- Plugins/AutoRemoveStone.xml
- Plugins/JumpSelector.xml
Reverts sepluginloader/PluginHub#370
We cannot change the GitHub path, because it is used as the "key" for subscriptions and stats. Users would be kicked out.
> Revert "Updated Dudes Plugins"

- Plugins/SeamlessClient.xml
Another possible fix for: 
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Sandbox.Game.EntityComponents.MyTargetLockingComponent.Update()
at Sandbox.Game.Entities.Character.MyCharacter.UpdateAfterSimulation10()
at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateAfterSimulation10()
The Parrallel Orchestrator is now being cleared on unload to remove any lingering entity updates that are non-existent. Possible cause was entities were removed but queued updates were still in the middle of updating. Fixes the above issue as well as other one off crashes from random entity crashes.
> v3.0.0.9 Update

- Plugins/HeadTrackingPlus.xml
- Plugins/Mods/HideCharacterInSeat.xml
Updated version of SEHeadtrackingPlugin
> Add HeadTrackingPlus
